### ISSUE TITLE
hosting of a public instance

### ISSUE THREAD

**Issue by wyattscarpenter** [madiele/TwitchToPodcastRSS#5]
While we're all waiting on https://github.com/lzeke0/TwitchRSS/issues/17 to be closed, would you think about hosting your fork online, somewhere where we can all send requests to the url?

If it's too much trouble, I could do it myself, but I figure it might be less trouble for you than me.

**Comment by madiele** [comment]
Currently I don't have plans for it, mostly because I'm pretty tight on money right now to host stuff, but in the future I probably will as I like the idea. (though I saw that https://github.com/lzeke0/TwitchRSS/issues/17 just merged it so the original should come back soon)

for anyone who plans to host it publicly be sure to edit the code so that `construct_rss()` is always called with `links_only=True`, I will edit the code later in the week so that you can do so with and env. variable. The reason being that it uses streamlink api keys (I have a branch ready to use ours instead but due to streamlink still using the old API merging can't be done right now)

**Comment by wyattscarpenter** [comment]
Thanks for the consideration! As the other public service has incorporated your changes and works great, this issue is resolved for me and I will close this issue (though you should feel free to reopen it if it is in your own interest too).

Just as a fun fact for if you ever get interested in hosting anything in the future, I use the free tier of Heroku to host my Discord bot https://github.com/wyattscarpenter/knowledge-lamborghini and it works pretty well.

Cheers!

**Comment by madiele** [comment]
yeah I know about Heroku free tier, unfortunately I already use it for a personal telegram bot I made, so it's not an option

**Comment by fdelucchijr** [comment]
> for anyone who plans to host it publicly be sure to edit the code so that `construct_rss()` is always called with `links_only=True`, I will edit the code later in the week so that you can do so with and env. variable. The reason being that it uses streamlink api keys (I have a branch ready to use ours instead but due to streamlink still using the old API merging can't be done right now)

Is still needed this change in the code? I already have transcoding disabled in env. 
My instance in publicly available but I want to mask the domain (is a dom I use for my personal/home projects) in order to protect the correlation of my profile with the domain. For now If you @madiele @wyattscarpenter has a discord or etc I can send you DM with the current domain and path.

**Comment by madiele** [comment]
@fdelucchijr checkout my other repository vod2pod-rss, it's a rewrite in rust of this repo that also adds the option to fully disable transcoding and adds youtube support, it's still in beta but I'm planning to release the 1.0 this week or the next, it's basically done and ready for use
